platform :ios, '8.0'

target 'EasyMVVM_Example' do
  use_frameworks!
  pod 'EasyMVVM', :path => '../'
  pod 'EasyAction', :git => 'git@github.com:Meituan-Dianping/EasyAction.git', :branch => 'master'
  
  target 'EasyMVVM_ExampleTests' do
    inherit! :search_paths
    pod 'Quick', '~>1.1.0'
    pod 'Nimble', '~>7.0.1'
    pod 'OCMock'
  end
  
  target 'EasyMVVM_ExampleUITests' do
      inherit! :search_paths
      pod 'Quick', '~>1.1.0'
      pod 'Nimble', '~>7.0.1'
  end
end

